// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edagghrxmvmevfkpyrsj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkYWdnaHJ4bXZtZXZma3B5cnNqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5MTY4MjIsImV4cCI6MjA2MTQ5MjgyMn0.jEe6Kck6pRXPcAq0Ee9K-_Z6g_pK6_EpMLIvKt5L0Wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);